declare const channel: BroadcastChannel;
declare let activetab: boolean;
declare const taskbar: Taskbar;
declare const launcher: Launcher;
declare const contextMenu: ContextMenu;
declare const oobeview: OobeView;
declare const alttab: AltTabView;
declare let anura: Anura;
declare function bootx86(): Promise<void>;
